on:
  schedule:
    - cron:  '5 * * * *'
  workflow_dispatch:
    description:
        description: 'Workflow Dispatch Description'

name: CRAN Snapshot

env:
  # otherwise remotes::fun() errors cause the build to fail. Example: Unavailability of binaries
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
  CRAN: release
  # use GITHUB_TOKEN from GitHub to workaround rate limits in {remotes}
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cran_snapshot:
    name: CRAN Snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.2'
      - name: Install dependencies
        run: |
          /usr/bin/sudo DEBIAN_FRONTEND=noninteractive apt-get update -qq
          /usr/bin/sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libcurl4-openssl-dev
          Rscript -e 'install.packages("https://github.com/r-lib/remotes/archive/master.tar.gz", repos = NULL)'
          Rscript -e 'install.packages(c("assertthat", "git2r", "yaml", "dplyr", "tidyr", "magrittr", "purrr", "curl", "prettyunits", "reactable", "glue", "tibble", "lubridate", "ps"), repos = "https://cran.rstudio.com")'
          Rscript -e 'remotes::install_github("ropensci/git2rdata")'
          Rscript -e 'remotes::install_github("lockedata/cransays")'
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ hashFiles('DESCRIPTION') }}
      - name: git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "cran snapshot committer"
      - name: Take CRAN Snapshot
        run: |
          git checkout main
          Rscript snapshot.R
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:main
